# Generated by Django 3.2.6 on 2021-08-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20210823_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket_elem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
