# Generated by Django 3.2.6 on 2021-08-25 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationuser', '0001_initial'),
        ('basket', '0004_basket_elem_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='basket_elem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='basket_elem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticationuser.customer'),
        ),
    ]
