# Generated by Django 3.2.6 on 2021-08-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationuser', '0001_initial'),
        ('basket', '0008_remove_basket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticationuser.customer'),
        ),
    ]
