# Generated by Django 3.2.6 on 2021-08-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
