# Generated by Django 3.2.6 on 2021-08-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_auto_20210804_1005'),
        ('basket', '0002_basket_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
        migrations.AddField(
            model_name='basket',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='basket_elem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.basket')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.product')),
            ],
        ),
    ]
