# Generated by Django 3.2.6 on 2021-08-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20210826_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='customer',
        ),
    ]
