# Generated by Django 3.2.6 on 2021-08-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_basket_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Customer',
            new_name='customer',
        ),
    ]
